//! The `Node` struct — the atomic unit of document data.
//!
//! Mirrors the PRD spec:
//!
//! ```text
//! Node {
//!     UUID id;
//!     TypeId type;
//!     Properties properties;
//!     LocalRelations relations;
//!     Metadata metadata;
//! }
//! ```
//!
//! Design notes:
//! - `id` is generated by the framework, never by the developer ("No ID
//!   management" rule from the developer-experience doc).
//! - `type_id` is a string newtype (`TypeId`) rather than an index —
//!   plugin-defined node types are registered by name at runtime.
//! - `LocalRelations` stores *per-node edge caches* keyed by relation
//!   schema name. The global edge set lives in `core/graph/storage.rs`
//!   (Phase 1, separate file). Keeping a local cache lets a node answer
//!   "who are my children?" without a graph lookup.
//! - Nodes are `Clone` so the History stack (Phase 2) can snapshot them
//!   cheaply. For million-node documents we will switch to
//!   copy-on-write handles; that is a Phase 5 concern.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::metadata::Metadata;
use super::properties::Properties;

/// Globally-unique node identifier. O(1) lookup in the graph storage.
pub type NodeId = Uuid;

/// Stringly-typed node-type identifier, e.g. `"TaskNode"`, `"UserNode"`.
///
/// This is a newtype (rather than a bare `String`) so that:
/// - Call sites read as `TypeId::new("TaskNode")` instead of opaque strings.
/// - We can swap the inner representation for an interned `&'static str`
///   later without touching call sites.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TypeId(pub String);

impl TypeId {
    #[inline]
    pub fn new(name: impl Into<String>) -> Self {
        Self(name.into())
    }

    #[inline]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for TypeId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl std::fmt::Display for TypeId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Per-node cache of outgoing edges, keyed by relation schema name
/// (e.g. `"CHILDREN"`, `"REFERENCE"`, `"BLOCKED_BY"`).
///
/// The schema name is resolved against the `RelationPresetRegistry`
/// (see `core::relation::presets`) by the graph layer when edges are
/// created or validated. Storing only the name here keeps `Node`
/// decoupled from the schema registry and trivially serializable.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LocalRelations {
    edges: HashMap<String, Vec<NodeId>>,
}

impl LocalRelations {
    pub fn new() -> Self {
        Self::default()
    }

    /// Append a target node to the named relation. The graph layer is
    /// responsible for enforcing topology / cardinality before calling
    /// this; `LocalRelations` itself is a dumb store.
    pub fn add(&mut self, schema_name: impl Into<String>, target: NodeId) {
        self.edges.entry(schema_name.into()).or_default().push(target);
    }

    /// Remove the first occurrence of `target` under `schema_name`.
    /// Returns `true` if a target was removed.
    pub fn remove(&mut self, schema_name: &str, target: NodeId) -> bool {
        if let Some(vec) = self.edges.get_mut(schema_name) {
            if let Some(pos) = vec.iter().position(|x| *x == target) {
                vec.remove(pos);
                if vec.is_empty() {
                    self.edges.remove(schema_name);
                }
                return true;
            }
        }
        false
    }

    /// All targets under a given relation schema, in insertion order.
    pub fn get(&self, schema_name: &str) -> &[NodeId] {
        self.edges
            .get(schema_name)
            .map(|v| v.as_slice())
            .unwrap_or(&[])
    }

    /// Iterate `(schema_name, targets)` pairs.
    pub fn iter(&self) -> impl Iterator<Item = (&String, &Vec<NodeId>)> {
        self.edges.iter()
    }

    /// `true` if any edge exists under `schema_name`.
    pub fn has(&self, schema_name: &str) -> bool {
        self.edges
            .get(schema_name)
            .map_or(false, |v| !v.is_empty())
    }

    /// Number of distinct relation schemas on this node.
    pub fn len_schemas(&self) -> usize {
        self.edges.len()
    }

    pub fn is_empty(&self) -> bool {
        self.edges.is_empty()
    }

    /// Clear every outgoing edge. Used by `DeleteNode` command cleanup.
    pub fn clear(&mut self) {
        self.edges.clear();
    }

		/// Remove a specific target node from all relation schemas.
    /// Used by `Graph::remove_node` to clean up the local cache.
    pub fn remove_all_targets(&mut self, target: NodeId) {
        for targets in self.edges.values_mut() {
            targets.retain(|t| *t != target);
        }
        self.edges.retain(|_, targets| !targets.is_empty());
    }
}

/// A single document object. Pure data — no behavior.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    /// Auto-generated; framework-owned. Never set manually by developers.
    pub id: NodeId,
    /// Resolved against the node-type registry (e.g. `"TaskNode"`).
    pub type_id: TypeId,
    /// Polymorphic property bag, partitioned by `PropertyKind`.
    pub properties: Properties,
    /// Outgoing edge cache (see `LocalRelations`).
    pub relations: LocalRelations,
    /// Tags, timestamps, version, dirty flag.
    pub metadata: Metadata,
}

impl Node {
    /// Create a new node with a fresh UUID and `Metadata::now()`.
    pub fn new(type_id: impl Into<String>) -> Self {
        Self {
            id: Uuid::new_v4(),
            type_id: TypeId::new(type_id),
            properties: Properties::new(),
            relations: LocalRelations::new(),
            metadata: Metadata::now(),
        }
    }

    /// Create a node with a caller-supplied ID. Used **only** by the
    /// deserializer (Phase 5) to preserve IDs across save/load.
    pub fn with_id(id: NodeId, type_id: impl Into<String>) -> Self {
        let mut node = Self::new(type_id);
        node.id = id;
        node
    }

    // ---- builder-style property setters (used by tests & scripts) ----

    #[must_use]
    pub fn set_persistent(
        mut self,
        name: impl Into<String>,
        value: super::properties::PropertyValue,
    ) -> Self {
        self.properties.set_persistent(name, value);
        self
    }

    #[must_use]
    pub fn set_transient(
        mut self,
        name: impl Into<String>,
        value: super::properties::PropertyValue,
    ) -> Self {
        self.properties.set_transient(name, value);
        self
    }

    #[must_use]
    pub fn add_tag(mut self, tag: impl Into<String>) -> Self {
        self.metadata.add_tag(tag);
        self
    }

    /// Bump `modified_at` and version, mark dirty. Called by the
    /// Command pipeline after a successful mutation.
    pub fn touch(&mut self) {
        self.metadata.touch();
    }

    /// Mark the node clean (e.g. after serialization to disk).
    pub fn mark_clean(&mut self) {
        self.metadata.mark_clean();
    }

    /// Convenience accessor mirroring the script syntax `node[id].title`.
    pub fn get(&self, name: &str) -> Option<&super::properties::PropertyValue> {
        self.properties.get_value(name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::node::properties::PropertyValue;

    #[test]
    fn new_node_gets_fresh_uuid_and_metadata() {
        let a = Node::new("TaskNode");
        let b = Node::new("TaskNode");
        assert_ne!(a.id, b.id);
        assert_eq!(a.type_id.as_str(), "TaskNode");
        assert!(!a.metadata.dirty);
        assert!(a.relations.is_empty());
    }

    #[test]
    fn with_id_preserves_supplied_id() {
        let id = Uuid::new_v4();
        let n = Node::with_id(id, "UserNode");
        assert_eq!(n.id, id);
        assert_eq!(n.type_id.as_str(), "UserNode");
    }

    #[test]
    fn local_relations_add_remove() {
        let mut n = Node::new("TaskNode");
        let c1 = Uuid::new_v4();
        let c2 = Uuid::new_v4();

        n.relations.add("CHILDREN", c1);
        n.relations.add("CHILDREN", c2);
        assert_eq!(n.relations.get("CHILDREN"), &[c1, c2]);
        assert!(n.relations.has("CHILDREN"));

        assert!(n.relations.remove("CHILDREN", c1));
        assert_eq!(n.relations.get("CHILDREN"), &[c2]);

        // Removing the last entry should drop the schema key entirely.
        assert!(n.relations.remove("CHILDREN", c2));
        assert!(!n.relations.has("CHILDREN"));
        assert!(n.relations.is_empty());
    }

    #[test]
    fn builder_pattern_chains() {
        let n = Node::new("TaskNode")
            .set_persistent("title", PropertyValue::String("Buy milk".into()))
            .set_transient("uiSelected", PropertyValue::Bool(true))
            .add_tag("urgent");

        assert_eq!(
            n.get("title"),
            Some(&PropertyValue::String("Buy milk".into()))
        );
        assert!(n.metadata.has_tag("urgent"));
        assert_eq!(
            n.properties.get("uiSelected").unwrap().kind,
            super::super::properties::PropertyKind::Transient,
        );
    }

    #[test]
    fn touch_bumps_version_and_sets_dirty() {
        let mut n = Node::new("TaskNode");
        let v0 = n.metadata.version;
        let m0 = n.metadata.modified_at;

        std::thread::sleep(std::time::Duration::from_millis(2));
        n.touch();

        assert!(n.metadata.dirty);
        assert_eq!(n.metadata.version, v0 + 1);
        assert!(n.metadata.modified_at > m0);

        n.mark_clean();
        assert!(!n.metadata.dirty);
    }
}