// web/app.js

// 1. Simple Web Component to render a node
class GdfNode extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  update(nodeData) {
    this._data = nodeData;
    this.render();
  }

  render() {
    const { tag, text, bounds, event_listeners } = this._data;

    this.style.position = 'absolute';
    this.style.left = `${bounds[0]}px`;
    this.style.top = `${bounds[1]}px`;
    this.style.width = `${bounds[2]}px`;
    this.style.height = `${bounds[3]}px`;
    this.style.boxSizing = 'border-box';

    let innerHtml = `<${tag} style="width: 100%; height: 100%;">`;
    if (text) innerHtml += text;
    innerHtml += `</${tag}>`;
    this.shadowRoot.innerHTML = innerHtml;

    const innerEl = this.shadowRoot.querySelector(tag);
    
    if (event_listeners && event_listeners.length > 0) {
      event_listeners.forEach(eventType => {
        innerEl.addEventListener(eventType, (e) => {
          e.preventDefault();
          let payload = { type: eventType, target: this.id };
          if (eventType === 'input') payload.value = e.target.value;
          
          // Dispatch event to the main app
          window.dispatchEvent(new CustomEvent('gdf-input', { detail: payload }));
        });
      });
    }

    // Render children
    if (this._data.children) {
      this._data.children.forEach(childData => {
        const childEl = document.createElement('gdf-node');
        childEl.id = childData.id;
        childEl.update(childData);
        this.shadowRoot.appendChild(childEl);
      });
    }
  }
}
customElements.define('gdf-node', GdfNode);

// 2. Main App Logic
async function run() {
  // Import the WASM module generated by wasm-pack
  const wasm = await import('/pkg/graph_document_framework.js');
  
  // Initialize the WASM binary (fetches and compiles the .wasm file)
  await wasm.default();
  
  // Initialize the Rust graph engine in memory
  wasm.init_app();
  
  const rootElement = document.getElementById('gdf-root');
  
  // Function to fetch UI from Rust and render it
  function renderUI() {
    const uiJson = wasm.get_ui_state();
    const rootNode = JSON.parse(uiJson);
    
    // Clear root and render
    rootElement.innerHTML = '';
    const rootEl = document.createElement('gdf-node');
    rootEl.id = rootNode.id;
    rootEl.update(rootNode);
    rootElement.appendChild(rootEl);
  }

  // Listen for events from the Web Components
  window.addEventListener('gdf-input', (e) => {
    // Send the event directly to Rust in memory!
    wasm.handle_dom_event(JSON.stringify(e.detail));
    
    // After Rust processes the event, re-render the UI
    renderUI();
  });

  // Initial render
  renderUI();
}

run();